version: '3'

services:
  my-diary-backend:
    build: ./backend
    volumes:
      - ~/database/database.db:/app/database.db
    ports:
      - "8080:8080"
    restart: unless-stopped
    command: npm start